2020-05-15 20:36:07,659 ERROR: Exception on /send_an_email [GET] [in /home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/users/routes.py", line 69, in send_me_an_email
    form = SendMeAnEmail()
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/templates/users/send_an_email.html", line 1, in top-level template code
    {% extends 'layout.html' %}
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/templates/layout.html", line 55, in top-level template code
    {% block content %}{% endblock %}
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/templates/users/send_an_email.html", line 5, in block "content"
    {{ form.hidden_tag() }}
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-05-15 20:39:38,631 ERROR: Exception on /send_an_email [GET] [in /home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/users/routes.py", line 69, in send_me_an_email
    form = SendMeAnEmail()
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/templates/users/send_an_email.html", line 1, in top-level template code
    {% extends 'layout.html' %}
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/templates/layout.html", line 55, in top-level template code
    {% block content %}{% endblock %}
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/templates/users/send_an_email.html", line 5, in block "content"
    {{ form.hidden_tag() }}
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-05-15 20:39:56,993 ERROR: Exception on /send_an_email [GET] [in /home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/users/routes.py", line 69, in send_me_an_email
    form = SendMeAnEmail()
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/templates/users/send_an_email.html", line 1, in top-level template code
    {% extends 'layout.html' %}
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/templates/layout.html", line 55, in top-level template code
    {% block content %}{% endblock %}
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/templates/users/send_an_email.html", line 5, in block "content"
    {{ form.hidden_tag() }}
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
